INSERT INTO T_TEACHER(TEACHER_ID, TEACHER_NAME, TEACHER_LASTNAME, TEACHER_SUBJECTNAME)
        VALUES ('1', 'Alex', 'Petrof', 'English');
INSERT INTO T_TEACHER(TEACHER_ID, TEACHER_NAME, TEACHER_LASTNAME, TEACHER_SUBJECTNAME)
        VALUES ('2', 'Taras', 'Ivanoy', 'Italian');

